services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=liquibase_starter
    ports:
      - "5432:5432"

  app:
    image: app
    build: .
    ports:
      - "8080:8081"
      - "5003:5003"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5003

  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"