spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/liquibase_starter
    username: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
server:
  port: 8081
